name: Deploy Project
on:
  push:
    branches: [develop]
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18.17.1"
      - name: Building the project dev
        run: |
          cd /home/runner/work/marketplace-community/marketplace-community
          echo "export const ENTRYPOINT_LOCAL = 'https://api.dev.controleonline.com'" > ./src/config/entrypoint.local.js
          echo "export const DOMAIN_LOCAL = location.host" > ./src/config/domain.local.js
          echo "const env = {\
          OAUTH_GOOGLE_CLIENT_ID:'${{ secrets.OAUTH_GOOGLE_CLIENT_ID }}',\
          GMAPS_GOOGLE_CLIENT_ID:'${{ secrets.GMAPS_GOOGLE_CLIENT_ID }}',\
          NEW_RELIC:{\
            LICENSE_KEY:'${{ secrets.NEW_RELIC_LICENSE_KEY }}',\
            APPLICATION_ID:'${{ secrets.NEW_RELIC_APPLICATION_ID }}',\
            ACCOUNT_ID: '${{ secrets.NEW_RELIC_ACCOUNT_ID }}',\
            TRUST_KEY: '${{ secrets.NEW_RELIC_TRUST_KEY }}',\
            BEACON: '${{ secrets.NEW_RELIC_BEACON }}',\
            ERROR_BEACON: '${{ secrets.NEW_RELIC_ERROR_BEACON }}'\
          }\
          };\
          module.exports = { env };\
          " > ./src/config/env.local.js          
          yarn

          npx quasar build
          npx quasar build -m pwa
      - name: Copy to controleonline dev
        uses: horochx/deploy-via-scp@master
        with:
          local: /home/runner/work/marketplace-community/marketplace-community/dist/*
          remote: ~/sistemas/controleonline/display/dist
          host: dev.controleonline.com
          port: 22
          user: controleonline1
          key: ${{ secrets.LOCAWEB }} 
      - name: Update Controle Online      
        uses: appleboy/ssh-action@master
        with:
          host: dev.controleonline.com
          username: controleonline1
          key: ${{ secrets.LOCAWEB }}
          port: 22        
          script: |
                  cd ~/sistemas/controleonline/api
                  git checkout develop
                  git pull origin develop                
                  php composer.phar install --no-suggest
                  php bin/console doctrine:migrations:migrate --no-interaction                                   
